In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegressionCV
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv("datasets/student_multiple_binary_classification.csv")
df

   Student  StudyHours  Attendance  PreviousMarks Result
0    Aarav           2          70             38   Fail
1     Sita           3          75             45   Fail
2      Ram           4          80             52   Pass
3   Anisha           5          85             60   Pass
4    Rohan           6          90             68   Pass
5    Priya           7          92             75   Pass
6    Kiran           8          95             82   Pass
7    Nabin           4          78             55   Pass
8    Suman           5          82             63   Pass
9   Alisha           6          88             70   Pass
10  Roshan           3          72             48   Fail
11    Rita           4          79             50   Fail

In [4]:
df.isnull().sum()
df.columns

Index(['Student', 'StudyHours', 'Attendance', 'PreviousMarks', 'Result'], dtype='str')

In [17]:
x=df[['StudyHours', 'Attendance', 'PreviousMarks']]
x=x.to_numpy()

In [16]:
y=df['Result'].map({
    "Fail":0,
    "Pass":1
})
y=y.to_numpy()

In [18]:
x_tr,x_te,y_tr,y_te=train_test_split(x,y,test_size=0.2,random_state=42)

In [19]:
x_tr

array([[ 5, 82, 63],
       [ 7, 92, 75],
       [ 4, 80, 52],
       [ 3, 75, 45],
       [ 4, 79, 50],
       [ 6, 90, 68],
       [ 4, 78, 55],
       [ 5, 85, 60],
       [ 8, 95, 82]])

In [20]:
model=LogisticRegressionCV()

In [21]:
model.fit(x_tr,y_tr)

D:\ai_uddan\vir\Lib\site-packages\sklearn\linear_model\_logistic.py:2092: FutureWarning: The default value for l1_ratios will change from None to (0.0,) in version 1.10. From version 1.10 onwards, only array-like with values in [0, 1] will be allowed, None will be forbidden. To avoid this warning, explicitly set a value, e.g. l1_ratios=(0,).
  warnings.warn(
D:\ai_uddan\vir\Lib\site-packages\sklearn\linear_model\_logistic.py:2137: FutureWarning: The default value of the parameter 'scoring' will change from None, i.e. accuracy, to 'neg_log_loss' in version 1.11. To silence this warning, explicitly set the scoring parameter: scoring='neg_log_loss' for the new, scoring='accuracy' or scoring=None for the old default.
  warnings.warn(
D:\ai_uddan\vir\Lib\site-packages\sklearn\linear_model\_logistic.py:2150: FutureWarning: The fitted attributes of LogisticRegressionCV will be simplified in scikit-learn 1.10 to remove redundancy. Set`use_legacy_attributes=False` to enable the new behavior now, or set it to `True` to silence this warning during the transition period while keeping the deprecated behavior for the time being. The default value of use_legacy_attributes will change from True to False in scikit-learn 1.10. See the docstring of LogisticRegressionCV for more details.
  warnings.warn(
D:\ai_uddan\vir\Lib\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  warnings.warn(

LogisticRegressionCV()

In [22]:
from sklearn.metrics import accuracy_score

In [25]:
res=model.predict(x_te)

In [27]:
data={
    "actual":y_te,
    "predicted":res
}
df2=pd.DataFrame(data)
df2

   actual  predicted
0       0          0
1       1          1
2       0          0

In [28]:
pre=accuracy_score(y_te,res)
pre

1.0